### ISSUE TITLE
Feature request in export to HTML

### ISSUE THREAD

**Issue by dgrl** [LianJordaan/Conversation-Exporter#1]
Hi

I would like to request a new feature.
Sometimes you change the question or regenerate a new response, by doing such you will get multiple conversation histories in the same tab,

Export to HTML currently does not export these and would like to see if that would be possible.

**Comment by LianJordaan** [comment]
Thanks for the suggestion, I will start working on it right away.

**Comment by LianJordaan** [comment]
I just looked into how I can possibly do this, and it seems like it won't be easy, but I will try my best.

**Comment by dgrl** [comment]
Thanks
Im also busy trying to write a working code for this.

**Comment by LianJordaan** [comment]
I think I might just remake how the entire thing works..

**Comment by dgrl** [comment]
I dont know how the code you have now is but It might be wise to start over from scratch sometimes :-)

**Comment by LianJordaan** [comment]
Ye, im going to remake everything..

**Comment by LianJordaan** [comment]
I am sorry, I will not be able to fix this.
